import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildContractInventory } from './inventory';
import { renderContractGraph, renderContractIssues, renderContractList, renderProviderMatrix } from './render';
import type { ContractInventory, ContractIssue, ContractManifest } from './types';

function manifest(inventory: ContractInventory): ContractManifest {
  return Object.freeze({
    schemaVersion: 1,
    fingerprint: inventory.fingerprint,
    contracts: inventory.contracts,
    providers: inventory.providers,
  });
}

function generatedHeader(source: string): string {
  return [
    '<!-- Generated by Winzard Forge. -->',
    `<!-- Source: ${source}. -->`,
    '<!-- Do not edit directly. -->',
    '',
  ].join('\n');
}

function registrySource(inventory: ContractInventory): string {
  const value = manifest(inventory);
  return [
    '// Generated by Winzard Forge.',
    '// Do not edit directly.',
    '',
    `export const generatedContractFingerprint = ${JSON.stringify(inventory.fingerprint)};`,
    '',
    `export const generatedContractRegistry = ${JSON.stringify(value.contracts, null, 2)} as const;`,
    '',
    `export const generatedContractProviderRegistry = ${JSON.stringify(value.providers, null, 2)} as const;`,
    '',
    'export const generatedContractManifest = Object.freeze({',
    '  schemaVersion: 1 as const,',
    '  fingerprint: generatedContractFingerprint,',
    '  contracts: generatedContractRegistry,',
    '  providers: generatedContractProviderRegistry,',
    '});',
    '',
  ].join('\n');
}

function securityDocument(inventory: ContractInventory): string {
  const issues = inventory.issues.filter(({ area, code }) => area === 'security' || code.includes('SECRET') || code.includes('TENANT') || code.includes('CONTAINER'));
  return [
    generatedHeader('contract definitions and source analysis'),
    '# Contract security status',
    '',
    `Contract SHA-256: \`${inventory.fingerprint}\``,
    '',
    issues.length === 0 ? 'PASS: No contract security issue detected.' : renderContractIssues(issues, 'contract security'),
    '',
  ].join('\n');
}

function deprecationDocument(inventory: ContractInventory): string {
  const deprecated = inventory.contracts.filter(({ stability }) => stability === 'deprecated');
  return [
    generatedHeader('contract lifecycle metadata'),
    '# Contract deprecation status',
    '',
    `Contract SHA-256: \`${inventory.fingerprint}\``,
    '',
    ...(deprecated.length === 0 ? ['No deprecated contracts.'] : [
      '| Contract | Since | Removal | Replacement | Migration |',
      '| --- | --- | --- | --- | --- |',
      ...deprecated.map((contract) => `| \`${contract.id}\` | ${contract.deprecation?.since ?? '-'} | ${contract.deprecation?.removal ?? '-'} | ${contract.deprecation?.replacement ? `\`${contract.deprecation.replacement}\`` : '-'} | ${contract.deprecation?.migration ? `\`${contract.deprecation.migration}\`` : '-'} |`),
    ]),
    '',
  ].join('\n');
}

export function contractArtifactContents(inventory: ContractInventory): Readonly<Record<string, string>> {
  const contractManifest = manifest(inventory);
  return Object.freeze({
    'src/generated/contracts/registry.ts': registrySource(inventory),
    'src/generated/contracts/contract-manifest.json': `${JSON.stringify(contractManifest, null, 2)}\n`,
    'docs/90-generated/contracts/contract-inventory.md': [
      generatedHeader('*.contract.definition.ts'),
      '# Contract inventory',
      '',
      `Contract SHA-256: \`${inventory.fingerprint}\``,
      '',
      renderContractList(inventory),
      '',
    ].join('\n'),
    'docs/90-generated/contracts/provider-matrix.md': [
      generatedHeader('*.contract-provider.ts'),
      '# Contract provider matrix',
      '',
      `Contract SHA-256: \`${inventory.fingerprint}\``,
      '',
      renderProviderMatrix(inventory),
      '',
    ].join('\n'),
    'docs/90-generated/contracts/contract-graph.md': [
      generatedHeader('contract and provider inventory'),
      '# Contract graph',
      '',
      `Contract SHA-256: \`${inventory.fingerprint}\``,
      '',
      '```mermaid',
      renderContractGraph(inventory, 'mermaid'),
      '```',
      '',
    ].join('\n'),
    'docs/90-generated/contracts/security-status.md': securityDocument(inventory),
    'docs/90-generated/contracts/deprecation-status.md': deprecationDocument(inventory),
  });
}

async function readOrNull(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateContracts(root: string): Promise<readonly string[]> {
  const inventory = await buildContractInventory(root);
  const written: string[] = [];
  for (const [projectFile, content] of Object.entries(contractArtifactContents(inventory))) {
    const target = path.join(root, projectFile);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
    written.push(projectFile);
  }
  return Object.freeze(written.sort());
}

export async function checkContractGeneration(root: string): Promise<readonly ContractIssue[]> {
  const inventory = await buildContractInventory(root);
  const issues: ContractIssue[] = [];
  for (const [projectFile, expected] of Object.entries(contractArtifactContents(inventory))) {
    const actual = await readOrNull(path.join(root, projectFile));
    if (actual !== expected) {
      issues.push(Object.freeze({
        severity: 'error',
        area: 'generation',
        code: 'CONTRACT_GENERATED_DRIFT',
        file: projectFile,
        message: actual === null ? 'A generált contract artefaktum hiányzik.' : 'A generált contract artefaktum eltér a canonical inventorytól.',
      }));
    }
  }
  return Object.freeze(issues.sort((left, right) => left.file.localeCompare(right.file)));
}
