import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source contract version: 1 -->',
  '<!-- Do not edit directly. -->',
].join('\n');

export function normalizeText(source: string): string {
  const normalized = source.replaceAll('\r\n', '\n');
  return normalized.endsWith('\n') ? normalized : `${normalized}\n`;
}

export function sha256(source: string | Buffer): string {
  return `sha256:${createHash('sha256').update(source).digest('hex')}`;
}

export async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function writeTextFile(filePath: string, content: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const temporary = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(temporary, normalizeText(content), 'utf8');
  await rename(temporary, filePath);
}

export async function writeJsonFile(filePath: string, value: unknown): Promise<void> {
  await writeTextFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export async function removeFileIfPresent(filePath: string): Promise<void> {
  await rm(filePath, { force: true });
}

export async function contentMatches(filePath: string, expected: string): Promise<boolean> {
  const current = await readOptional(filePath);
  return current !== null && normalizeText(current) === normalizeText(expected);
}
