function defineTestingContract<const T>(definition: T): T {
  return definition;
}

export const testingDefinition = defineTestingContract({
  schemaVersion: 1,
  suites: [
    {
      id: 'reference.unit',
      owner: 'app:reference',
      layer: 'unit',
      runtime: 'node',
      command: 'pnpm test:unit',
      include: ['apps/reference/tests/unit/**/*.test.ts'],
      sources: ['apps/reference/src/**/*.ts', 'apps/reference/src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core', 'reference-app'],
      services: [],
      ciJob: 'testing / unit-contract',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: true,
    },
    {
      id: 'forge.unit',
      owner: 'package:forge',
      layer: 'unit',
      runtime: 'node',
      command: 'pnpm test:unit',
      include: ['packages/forge/tests/**/*.test.ts'],
      sources: ['packages/forge/src/**/*.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'forge-development'],
      services: [],
      ciJob: 'testing / unit-contract',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: true,
    },
    {
      id: 'forge.contract',
      owner: 'package:forge',
      layer: 'contract',
      runtime: 'node',
      command: 'pnpm test:contract',
      include: ['packages/forge/tests/**/*.contract.test.ts'],
      sources: ['packages/forge/src/testing/**/*.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'forge-development'],
      services: [],
      ciJob: 'testing / unit-contract',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: true,
    },
    {
      id: 'config.unit',
      owner: 'package:config',
      layer: 'unit',
      runtime: 'node',
      command: 'pnpm test:unit',
      include: ['packages/config/tests/**/*.test.ts'],
      sources: ['packages/config/src/**/*.ts'],
      fixtures: [],
      capabilities: ['testing-core'],
      services: [],
      ciJob: 'testing / unit-contract',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: true,
    },
    {
      id: 'minimal.unit',
      owner: 'template:minimal',
      layer: 'unit',
      runtime: 'node',
      command: 'vitest run --config templates/minimal/vitest.config.ts',
      include: ['templates/minimal/tests/unit/**/*.test.ts'],
      sources: ['templates/minimal/src/**/*.ts', 'templates/minimal/src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core'],
      services: [],
      ciJob: 'verify / core',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'webapp.unit',
      owner: 'template:webapp',
      layer: 'unit',
      runtime: 'node',
      command: 'vitest run --config templates/webapp/vitest.config.ts',
      include: ['templates/webapp/tests/unit/**/*.test.ts'],
      sources: ['templates/webapp/src/**/*.ts', 'templates/webapp/src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core'],
      services: [],
      ciJob: 'verify / database',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'webapp.database',
      owner: 'template:webapp',
      layer: 'integration',
      runtime: 'postgresql',
      command: 'pnpm test:database',
      include: ['templates/webapp/tests/integration/**/*.test.ts'],
      sources: ['templates/webapp/src/platform/database/**/*.ts', 'templates/webapp/src/platform/messaging/**/*.ts', 'templates/webapp/prisma/**'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-database', 'prisma-postgresql'],
      services: ['postgresql'],
      ciJob: 'testing / database-contract',
      duration: 'medium',
      serial: true,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.component',
      owner: 'app:reference',
      layer: 'integration',
      runtime: 'jsdom',
      command: 'pnpm test:component',
      include: ['apps/reference/tests/component/**/*.test.tsx'],
      sources: ['apps/reference/src/platform/ui/**/*.tsx', 'apps/reference/src/modules/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-dom'],
      services: [],
      ciJob: 'testing / component',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.application-http',
      owner: 'app:reference',
      layer: 'application-http',
      runtime: 'node',
      command: 'pnpm test:application',
      include: ['apps/reference/tests/e2e/**/*.smoke.ts'],
      sources: ['apps/reference/src/app/**/*.ts', 'apps/reference/src/app/**/*.tsx', 'apps/reference/src/platform/http/**/*.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'next-app'],
      services: ['next-production-server'],
      ciJob: 'verify / core',
      duration: 'medium',
      serial: true,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.browser',
      owner: 'app:reference',
      layer: 'browser-e2e',
      runtime: 'browser',
      command: 'pnpm test:e2e',
      include: ['apps/reference/tests/browser/**/*.spec.ts'],
      sources: ['apps/reference/src/**/*.ts', 'apps/reference/src/**/*.tsx', 'playwright.config.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-e2e'],
      services: ['next-production-server', 'chromium'],
      ciJob: 'testing / browser-accessibility',
      duration: 'slow',
      serial: false,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.accessibility',
      owner: 'app:reference',
      layer: 'accessibility',
      runtime: 'browser',
      command: 'pnpm test:a11y',
      include: ['apps/reference/tests/browser/**/*.spec.ts'],
      sources: ['apps/reference/src/**/*.tsx', 'playwright.config.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-e2e', 'testing-accessibility'],
      services: ['next-production-server', 'chromium'],
      ciJob: 'testing / browser-accessibility',
      duration: 'slow',
      serial: false,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
  ],
  quarantine: [],
} as const);
