function defineTestingContract<const T>(definition: T): T {
  return definition;
}

export const testingDefinition = defineTestingContract({
  schemaVersion: 1,
  suites: [
    {
      id: 'reference.unit',
      owner: 'app:reference',
      layer: 'unit',
      runtime: 'node',
      command: 'pnpm test:unit',
      include: ['tests/unit/**/*.test.ts'],
      sources: ['src/**/*.ts', 'src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core'],
      services: [],
      ciJob: 'testing / unit-contract',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: true,
    },
    {
      id: 'reference.component',
      owner: 'app:reference',
      layer: 'integration',
      runtime: 'jsdom',
      command: 'pnpm test:component',
      include: ['tests/component/**/*.test.tsx'],
      sources: ['src/platform/ui/**/*.tsx', 'src/modules/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-dom'],
      services: [],
      ciJob: 'testing / component',
      duration: 'fast',
      serial: false,
      productionBuild: false,
      healthcheck: null,
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.application-http',
      owner: 'app:reference',
      layer: 'application-http',
      runtime: 'node',
      command: 'pnpm test:application',
      include: ['tests/e2e/**/*.smoke.ts'],
      sources: ['src/app/**/*.ts', 'src/app/**/*.tsx', 'src/platform/http/**/*.ts'],
      fixtures: [],
      capabilities: ['testing-core', 'next-app'],
      services: ['next-production-server'],
      ciJob: 'verify / core',
      duration: 'medium',
      serial: true,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.browser',
      owner: 'app:reference',
      layer: 'browser-e2e',
      runtime: 'browser',
      command: 'pnpm test:e2e',
      include: ['tests/browser/**/*.spec.ts'],
      sources: ['src/**/*.ts', 'src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-e2e'],
      services: ['next-production-server', 'chromium'],
      ciJob: 'testing / browser-accessibility',
      duration: 'slow',
      serial: false,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
    {
      id: 'reference.accessibility',
      owner: 'app:reference',
      layer: 'accessibility',
      runtime: 'browser',
      command: 'pnpm test:a11y',
      include: ['tests/browser/**/*.spec.ts'],
      sources: ['src/**/*.tsx'],
      fixtures: [],
      capabilities: ['testing-core', 'testing-e2e', 'testing-accessibility'],
      services: ['next-production-server', 'chromium'],
      ciJob: 'testing / browser-accessibility',
      duration: 'slow',
      serial: false,
      productionBuild: true,
      healthcheck: '/api/health/live',
      network: 'blocked',
      coverage: false,
    },
  ],
  quarantine: [],
} as const);
