CREATE TABLE "OutboxMessage" ("id" TEXT NOT NULL, "source" TEXT NOT NULL, "type" TEXT NOT NULL, "subject" TEXT, "schemaVersion" INTEGER NOT NULL, "aggregateId" TEXT, "aggregateSequence" BIGINT, "tenantId" TEXT, "correlationId" TEXT, "causationId" TEXT, "payload" JSONB NOT NULL, "metadata" JSONB NOT NULL, "status" TEXT NOT NULL DEFAULT 'pending', "attempts" INTEGER NOT NULL DEFAULT 0, "availableAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lockedAt" TIMESTAMP(3), "lockedBy" TEXT, "publishedAt" TIMESTAMP(3), "lastErrorCode" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OutboxMessage_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "OutboxMessage_source_id_key" ON "OutboxMessage"("source", "id");
CREATE INDEX "OutboxMessage_status_availableAt_idx" ON "OutboxMessage"("status", "availableAt");
CREATE INDEX "OutboxMessage_aggregateId_aggregateSequence_idx" ON "OutboxMessage"("aggregateId", "aggregateSequence");
CREATE TABLE "InboxMessage" ("consumerId" TEXT NOT NULL, "source" TEXT NOT NULL, "eventId" TEXT NOT NULL, "tenantId" TEXT, "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resultHash" TEXT, CONSTRAINT "InboxMessage_pkey" PRIMARY KEY ("consumerId", "source", "eventId"));
CREATE INDEX "InboxMessage_tenantId_processedAt_idx" ON "InboxMessage"("tenantId", "processedAt");
CREATE TABLE "DeadLetterMessage" ("id" TEXT NOT NULL, "consumerId" TEXT, "source" TEXT NOT NULL, "eventId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "schemaVersion" INTEGER NOT NULL, "attemptCount" INTEGER NOT NULL, "firstFailureAt" TIMESTAMP(3) NOT NULL, "lastFailureAt" TIMESTAMP(3) NOT NULL, "errorCode" TEXT NOT NULL, "payloadHash" TEXT NOT NULL, "correlationId" TEXT, "tenantId" TEXT, "operatorAction" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DeadLetterMessage_pkey" PRIMARY KEY ("id"));
CREATE INDEX "DeadLetterMessage_consumerId_lastFailureAt_idx" ON "DeadLetterMessage"("consumerId", "lastFailureAt");
CREATE INDEX "DeadLetterMessage_tenantId_lastFailureAt_idx" ON "DeadLetterMessage"("tenantId", "lastFailureAt");
