import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildViewInventory } from './inventory';
import type { ViewInventory, ViewIssue, ViewRecord } from './types';

const GENERATED_HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: presentation components, App Router view boundaries and static TypeScript inspection. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function hashInventory(inventory: ViewInventory): string {
  return createHash('sha256').update(JSON.stringify(inventory)).digest('hex');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function valueList(values: readonly string[]): string {
  return values.length === 0 ? '-' : values.map((value) => `\`${escapeCell(value)}\``).join('<br>');
}

function mapDocument(inventory: ViewInventory): string {
  const rows = inventory.records.map((record) =>
    `| ${record.kind} | ${record.boundary} | \`${escapeCell(record.name)}\` | \`${escapeCell(record.route ?? '-')}\` | \`${escapeCell(record.file)}\` | ${record.async ? 'yes' : 'no'} |`,
  );
  return `${GENERATED_HEADER}\n\n# View map\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Kind | Boundary | Name | Route | File | Async |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - |'}\n`;
}

function contractDocument(inventory: ViewInventory): string {
  const rows = inventory.records.map((record) =>
    `| \`${escapeCell(record.name)}\` | \`${escapeCell(record.file)}\` | \`${escapeCell(record.propsType ?? '-')}\` | ${valueList(record.props)} | ${valueList(record.viewModels)} | ${valueList(record.routeBuilders)} | ${valueList(record.tests)} |`,
  );
  return `${GENERATED_HEADER}\n\n# View contracts\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| View | File | Props type | Props | View models | Route builders | Tests |\n| --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - |'}\n`;
}

function imageList(record: ViewRecord): readonly string[] {
  return record.assets.images.map((image) =>
    `${image.kind}:${image.source ?? '<dynamic>'}:${image.hasAlt ? 'alt' : 'missing-alt'}`);
}

function assetDocument(inventory: ViewInventory): string {
  const rows = inventory.records.map((record) =>
    `| \`${escapeCell(record.name)}\` | ${valueList(imageList(record))} | ${valueList(record.assets.stylesheets)} | ${valueList(record.assets.fonts)} | ${valueList(record.assets.scripts)} | ${valueList(record.assets.staticAssets)} | ${valueList(record.assets.publicUrls)} | ${valueList(record.assets.externalUrls)} |`,
  );
  return `${GENERATED_HEADER}\n\n# View assets\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| View | Images | Stylesheets | Fonts | Scripts | Static imports | Public URLs | External URLs |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - | - |'}\n`;
}

function securityDocument(inventory: ViewInventory): string {
  const rows = inventory.issues.map((issue) =>
    `| ${issue.severity} | \`${issue.code}\` | \`${escapeCell(issue.file)}\` | ${escapeCell(issue.message)} |`,
  );
  return `${GENERATED_HEADER}\n\n# View security and architecture status\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Severity | Code | File | Message |\n| --- | --- | --- | --- |\n${rows.join('\n') || '| pass | - | - | No view issue detected. |'}\n`;
}

export function renderViewDocumentation(inventory: ViewInventory): Readonly<Record<string, string>> {
  return {
    'view-map.md': mapDocument(inventory),
    'view-contracts.md': contractDocument(inventory),
    'view-assets.md': assetDocument(inventory),
    'security-status.md': securityDocument(inventory),
  };
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateViewDocumentation(root = process.cwd()): Promise<readonly string[]> {
  const inventory = await buildViewInventory(root);
  const directory = path.join(root, 'docs/90-generated/views');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(renderViewDocumentation(inventory))) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/views/${name}`);
  }
  return written;
}

export async function checkViewDocumentation(root = process.cwd()): Promise<readonly ViewIssue[]> {
  const inventory = await buildViewInventory(root);
  const expected = renderViewDocumentation(inventory);
  const issues: ViewIssue[] = [];
  for (const [name, content] of Object.entries(expected)) {
    const file = `docs/90-generated/views/${name}`;
    const actual = await readOptional(path.join(root, file));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        code: actual === null ? 'VIEW_DOC_MISSING' : 'VIEW_DOC_DRIFT',
        file,
        message: actual === null
          ? 'A generált view dokumentum hiányzik.'
          : 'A generált view dokumentum nincs szinkronban a presentation forrásokkal.',
      });
    }
  }
  return issues;
}
