import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildDeliveryInventory } from './inventory';
import type { DeliveryInventory, DeliveryIssue } from './types';

const GENERATED_HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: Next.js delivery entrypoints and static TypeScript inspection. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function hashInventory(inventory: DeliveryInventory): string {
  return createHash('sha256').update(JSON.stringify(inventory)).digest('hex');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function valueList(values: readonly string[]): string {
  return values.length === 0 ? '-' : values.map((value) => `\`${escapeCell(value)}\``).join('<br>');
}

function deliveryMap(inventory: DeliveryInventory): string {
  const rows = inventory.records.map((record) =>
    `| ${record.kind} | ${record.methods.join(',') || '-'} | \`${escapeCell(record.route ?? '-')}\` | \`${escapeCell(record.entrypoint)}\` | ${record.runtime} | ${record.streaming ? 'yes' : 'no'} |`,
  );
  return `${GENERATED_HEADER}\n\n# Delivery map\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Kind | Method | Route | Entrypoint | Runtime | Streaming |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - |'}\n`;
}

function httpContracts(inventory: DeliveryInventory): string {
  const records = inventory.records;
  const rows = records.map((record) =>
    `| \`${escapeCell(record.entrypoint)}\` | ${valueList(record.inputSchemas)} | ${valueList(record.actorResolvers)} | ${valueList(record.authorizationCalls)} | ${valueList(record.applicationOperations)} | ${valueList(record.outputKinds)} | ${escapeCell(record.cachePolicy ?? '-')} | ${valueList(record.tests)} |`,
  );
  return `${GENERATED_HEADER}\n\n# HTTP and UI delivery contracts\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Entrypoint | Input schema | Actor | Authorization | Application operation | Output | Cache | Tests |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - | - |'}\n`;
}

function securityStatus(inventory: DeliveryInventory): string {
  const rows = inventory.issues.map((issue) =>
    `| ${issue.severity} | \`${issue.code}\` | \`${escapeCell(issue.file)}\` | ${escapeCell(issue.message)} |`,
  );
  return `${GENERATED_HEADER}\n\n# Delivery security status\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Severity | Code | File | Message |\n| --- | --- | --- | --- |\n${rows.join('\n') || '| pass | - | - | No delivery issue detected. |'}\n`;
}

export function renderDeliveryDocumentation(inventory: DeliveryInventory): Readonly<Record<string, string>> {
  return {
    'delivery-map.md': deliveryMap(inventory),
    'http-contracts.md': httpContracts(inventory),
    'security-status.md': securityStatus(inventory),
  };
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateDeliveryDocumentation(root = process.cwd()): Promise<readonly string[]> {
  const inventory = await buildDeliveryInventory(root);
  const directory = path.join(root, 'docs/90-generated/delivery');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(renderDeliveryDocumentation(inventory))) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/delivery/${name}`);
  }
  return written;
}

export async function checkDeliveryDocumentation(root = process.cwd()): Promise<readonly DeliveryIssue[]> {
  const inventory = await buildDeliveryInventory(root);
  const expected = renderDeliveryDocumentation(inventory);
  const issues: DeliveryIssue[] = [];
  for (const [name, content] of Object.entries(expected)) {
    const file = `docs/90-generated/delivery/${name}`;
    const actual = await readOptional(path.join(root, file));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        code: actual === null ? 'DELIVERY_DOC_MISSING' : 'DELIVERY_DOC_DRIFT',
        file,
        message: actual === null
          ? 'A generált delivery dokumentum hiányzik.'
          : 'A generált delivery dokumentum nincs szinkronban az entrypointokkal.',
      });
    }
  }
  return issues;
}
