import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildFormInventory, isFormAccessibilityIssue, isFormSecurityIssue } from './inventory';
import type { FormInventory, FormIssue } from './types';

const GENERATED_HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: static form definitions, TypeScript/TSX inspection and adjacent delivery contracts. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function list(values: readonly string[]): string {
  return values.length === 0 ? '-' : values.map((value) => `\`${escapeCell(value)}\``).join('<br>');
}

function mapDocument(inventory: FormInventory): string {
  const rows = inventory.records.map((record) =>
    `| \`${escapeCell(record.id)}\` | ${record.execution} | ${record.mutation ? 'yes' : 'no'} | \`${escapeCell(record.component)}\` | \`${escapeCell(record.deliveryContractId ?? '-')}\` | ${record.fields.length} | \`${escapeCell(record.file)}\` |`);
  return `${GENERATED_HEADER}\n\n# Form map\n\nInventory SHA-256: \`${inventory.fingerprint}\`\n\n| Form | Execution | Mutation | Component | Delivery contract | Fields | Definition |\n| --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - |'}\n`;
}

function contractDocument(inventory: FormInventory): string {
  const rows = inventory.records.map((record) =>
    `| \`${escapeCell(record.id)}\` | \`${escapeCell(record.extractor)}\` | \`${escapeCell(record.schema)}\` | \`${escapeCell(record.actionState)}\` | \`${escapeCell(record.errorMapper)}\` | ${record.unknownFields} | ${record.progressiveEnhancement} | ${list(record.intents.map(({ value }) => value))} | ${list(record.tests)} |`);
  return `${GENERATED_HEADER}\n\n# Form contracts\n\nInventory SHA-256: \`${inventory.fingerprint}\`\n\n| Form | Extractor | Schema | Action state | Error mapper | Unknown fields | Progressive enhancement | Intents | Tests |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - | - | - |'}\n`;
}

function fieldDocument(inventory: FormInventory): string {
  const rows = inventory.records.flatMap((record) => record.fields.map((field) =>
    `| \`${escapeCell(record.id)}\` | \`${escapeCell(field.name)}\` | \`${escapeCell(field.id)}\` | ${field.kind} | ${field.multiplicity} | ${field.required ? 'yes' : 'no'} | ${field.presentationOnly ? 'yes' : 'no'} | ${field.authority ? 'yes' : 'no'} |`));
  return `${GENERATED_HEADER}\n\n# Form fields\n\nInventory SHA-256: \`${inventory.fingerprint}\`\n\n| Form | Name | HTML ID | Kind | Multiplicity | Required | Presentation-only | Authority |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - | - | - |'}\n`;
}

function errorDocument(inventory: FormInventory): string {
  const rows = inventory.records.flatMap((record) => record.fields.flatMap((field) => field.errorCodes.map((code) =>
    `| \`${escapeCell(record.id)}\` | \`${escapeCell(field.name)}\` | \`${escapeCell(code)}\` |`)));
  return `${GENERATED_HEADER}\n\n# Form errors\n\nInventory SHA-256: \`${inventory.fingerprint}\`\n\n| Form | Field | Error code |\n| --- | --- | --- |\n${rows.join('\n') || '| - | - | - |'}\n`;
}

function statusDocument(inventory: FormInventory, title: string, selected: readonly FormIssue[]): string {
  const rows = selected.map((entry) =>
    `| ${entry.severity} | \`${escapeCell(entry.code)}\` | \`${escapeCell(entry.file)}\` | ${escapeCell(entry.message)} |`);
  return `${GENERATED_HEADER}\n\n# ${title}\n\nInventory SHA-256: \`${inventory.fingerprint}\`\n\n| Severity | Code | File | Message |\n| --- | --- | --- | --- |\n${rows.join('\n') || '| pass | - | - | No issue detected. |'}\n`;
}

export function renderFormDocumentation(inventory: FormInventory): Readonly<Record<string, string>> {
  return Object.freeze({
    'form-map.md': mapDocument(inventory),
    'form-contracts.md': contractDocument(inventory),
    'form-fields.md': fieldDocument(inventory),
    'form-errors.md': errorDocument(inventory),
    'accessibility-status.md': statusDocument(inventory, 'Form accessibility status', inventory.issues.filter(isFormAccessibilityIssue)),
    'security-status.md': statusDocument(inventory, 'Form security and architecture status', inventory.issues.filter(isFormSecurityIssue)),
  });
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateFormDocumentation(root = process.cwd()): Promise<readonly string[]> {
  const inventory = await buildFormInventory(root);
  const directory = path.join(root, 'docs/90-generated/forms');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(renderFormDocumentation(inventory))) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/forms/${name}`);
  }
  return Object.freeze(written);
}

export async function checkFormDocumentation(root = process.cwd()): Promise<readonly FormIssue[]> {
  const inventory = await buildFormInventory(root);
  const expected = renderFormDocumentation(inventory);
  const issues: FormIssue[] = [];
  for (const [name, content] of Object.entries(expected)) {
    const file = `docs/90-generated/forms/${name}`;
    const actual = await readOptional(path.join(root, file));
    if (actual !== content) {
      issues.push(Object.freeze({
        severity: 'error',
        code: actual === null ? 'FORM_DOC_MISSING' : 'FORM_DOC_DRIFT',
        file,
        message: actual === null
          ? 'A generált form dokumentum hiányzik.'
          : 'A generált form dokumentum nincs szinkronban a form contractokkal.',
      }));
    }
  }
  return Object.freeze(issues);
}
