import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildRouteInventory } from './inventory';
import type { RouteInventory, RoutingIssue } from './types';

const GENERATED_HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: Next.js App Router filesystem and static next.config aliases. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function hashInventory(inventory: RouteInventory): string {
  return createHash('sha256').update(JSON.stringify(inventory)).digest('hex');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function routeMap(inventory: RouteInventory): string {
  const rows = inventory.routes.map((route) => `| ${escapeCell(route.methods.join(',') || '-')} | ${route.kind} | \`${escapeCell(route.pattern)}\` | \`${escapeCell(route.entrypoint)}\` | ${route.runtime} | ${route.owner} |`);
  return `${GENERATED_HEADER}\n\n# Route map\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Method | Kind | Pattern | Entrypoint | Runtime | Owner |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - | - |'}\n`;
}

function redirectMap(inventory: RouteInventory): string {
  const rows = inventory.aliases.map((alias) => `| ${alias.type} | \`${escapeCell(alias.source)}\` | \`${escapeCell(alias.destination)}\` | ${alias.permanent === null ? '-' : String(alias.permanent)} | \`${alias.configFile}\` |`);
  return `${GENERATED_HEADER}\n\n# Redirect and rewrite map\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Type | Source | Destination | Permanent | Config |\n| --- | --- | --- | --- | --- |\n${rows.join('\n') || '| - | - | - | - | - |'}\n`;
}

function securityStatus(inventory: RouteInventory): string {
  const rows = inventory.issues.map((issue) => `| ${issue.severity} | \`${issue.code}\` | \`${escapeCell(issue.file)}\` | ${escapeCell(issue.message)} |`);
  return `${GENERATED_HEADER}\n\n# Routing check status\n\nInventory SHA-256: \`${hashInventory(inventory)}\`\n\n| Severity | Code | File | Message |\n| --- | --- | --- | --- |\n${rows.join('\n') || '| pass | - | - | No routing issue detected. |'}\n`;
}

export function renderRouteDocumentation(inventory: RouteInventory): Readonly<Record<string, string>> {
  return {
    'route-map.md': routeMap(inventory),
    'redirect-map.md': redirectMap(inventory),
    'security-status.md': securityStatus(inventory),
  };
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateRouteDocumentation(root = process.cwd()): Promise<readonly string[]> {
  const inventory = await buildRouteInventory(root);
  const directory = path.join(root, 'docs/90-generated/routing');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(renderRouteDocumentation(inventory))) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/routing/${name}`);
  }
  return written;
}

export async function checkRouteDocumentation(root = process.cwd()): Promise<readonly RoutingIssue[]> {
  const inventory = await buildRouteInventory(root);
  const expected = renderRouteDocumentation(inventory);
  const issues: RoutingIssue[] = [];
  for (const [name, content] of Object.entries(expected)) {
    const file = `docs/90-generated/routing/${name}`;
    const actual = await readOptional(path.join(root, file));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        code: actual === null ? 'ROUTE_DOC_MISSING' : 'ROUTE_DOC_DRIFT',
        file,
        message: actual === null ? 'A generált routing dokumentum hiányzik.' : 'A generált routing dokumentum nincs szinkronban a route-fával.',
      });
    }
  }
  return issues;
}
