import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildKernelInventory } from './inventory';
import type { KernelInventory, KernelIssue, KernelRecord } from './types';

const HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: adjacent delivery contracts, Next.js route inventory and static TypeScript inspection. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function sha256(inventory: KernelInventory): string {
  const canonical = JSON.stringify({
    schemaVersion: inventory.schemaVersion,
    sourceRoot: inventory.sourceRoot,
    records: inventory.records,
    issues: inventory.issues,
  });
  return createHash('sha256').update(canonical).digest('hex');
}

function cell(value: string | number | null | readonly string[]): string {
  if (value === null || value === '') return '-';
  if (Array.isArray(value)) {
    return value.length > 0
      ? value.map((item) => String(item).replaceAll('|', '\\|')).join('<br>')
      : '-';
  }
  return String(value).replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function mapCell(value: Readonly<Record<string, string>>): string {
  const entries = Object.entries(value).filter(([, item]) => item !== '');
  return entries.length > 0
    ? entries.map(([key, item]) => `${key}: ${item}`.replaceAll('|', '\\|')).join('<br>')
    : '-';
}

function routeOrActions(record: KernelRecord): string | readonly string[] {
  return record.route ?? record.actions;
}

function contracts(inventory: KernelInventory, hash: string): string {
  const rows = inventory.records.map((record) =>
    `| \`${record.id}\` | ${record.kind} | ${cell(routeOrActions(record))} | ${cell(record.methods)} | \`${record.entrypoint ?? '-'}\` | ${record.requestContext} | ${record.authentication} | ${record.tenant} | ${cell(record.rateLimit)} | ${cell(record.cache)} | ${cell(record.responsePolicy)} | ${cell(record.csrf)} | ${cell(record.idempotency)} | ${record.bodyLimitBytes ?? '-'} | ${record.streaming ? 'yes' : 'no'} | ${cell(record.tests)} |`,
  ).join('\n');
  return `${HEADER}\n\n# HTTP-kernel contracts\n\nInventory SHA-256: \`${hash}\`\n\n| ID | Kind | Route / actions | Methods | Entrypoint | Context | Auth | Tenant | Rate limit | Cache | Response | CSRF | Idempotency | Body limit | Streaming | Tests |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows}\n`;
}

function graph(inventory: KernelInventory, hash: string): string {
  const rows = inventory.records.map((record) =>
    `| ${cell(routeOrActions(record))} | \`${record.id}\` | ${record.requestContext} | ${mapCell(record.authorization)} | ${mapCell(record.operations)} | ${mapCell(record.presenters)} | ${cell(record.responsePolicy ?? record.cache)} | ${cell(record.afterHooks)} | ${cell(record.instrumentation)} |`,
  ).join('\n');
  return `${HEADER}\n\n# HTTP-kernel graph\n\nInventory SHA-256: \`${hash}\`\n\n| Route / action | Contract | Request context | Authorization | Application operation | Presenter | Response policy | After hooks | Instrumentation |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows}\n`;
}

function security(inventory: KernelInventory, hash: string): string {
  const rows = inventory.issues.length > 0
    ? inventory.issues.map((item) =>
      `| ${item.severity} | ${item.area} | \`${item.code}\` | \`${item.file}\` | ${item.message.replaceAll('|', '\\|').replaceAll('\n', '<br>')} |`,
    ).join('\n')
    : '| pass | - | - | - | No HTTP-kernel issue detected. |';
  return `${HEADER}\n\n# HTTP-kernel security status\n\nInventory SHA-256: \`${hash}\`\n\n| Severity | Area | Code | File | Message |\n| --- | --- | --- | --- | --- |\n${rows}\n`;
}

function lifecycleSection(record: KernelRecord): string {
  const location = typeof routeOrActions(record) === 'string'
    ? routeOrActions(record) as string
    : (routeOrActions(record) as readonly string[]).join(', ');
  return `## ${record.id}\n\n\`\`\`text\n${location || '-'}\n→ ${record.contractFile}\n→ enforcement: ${record.enforcement.join(', ') || '-'}\n→ request context: ${record.requestContextFactories.join(', ') || record.requestContext}\n→ authentication: ${record.authentication}\n→ tenant: ${record.tenant}\n→ authorization: ${mapCell(record.authorization).replaceAll('<br>', '; ')}\n→ rate limit: ${record.rateLimit ?? '-'}\n→ operation: ${mapCell(record.operations).replaceAll('<br>', '; ')}\n→ presenter: ${mapCell(record.presenters).replaceAll('<br>', '; ')}\n→ response policy: ${record.responsePolicy ?? record.cache ?? '-'}\n→ error mapping: ${record.errorMappers.join(', ') || '-'}\n→ after response: ${record.afterHooks.join(', ') || '-'}\n→ instrumentation: ${record.instrumentation.join(', ') || '-'}\n→ tests: ${record.tests.join(', ') || '-'}\n\`\`\`\n`;
}

function lifecycle(inventory: KernelInventory, hash: string): string {
  const sections = inventory.records.map(lifecycleSection).join('\n');
  return `${HEADER}\n\n# Request lifecycle evidence\n\nInventory SHA-256: \`${hash}\`\n\n${sections}`;
}

function expected(inventory: KernelInventory): Readonly<Record<string, string>> {
  const hash = sha256(inventory);
  return Object.freeze({
    'kernel-contracts.md': contracts(inventory, hash),
    'kernel-graph.md': graph(inventory, hash),
    'kernel-security-status.md': security(inventory, hash),
    'request-lifecycle.md': lifecycle(inventory, hash),
  });
}

async function readOptional(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateKernelDocumentation(root = process.cwd()): Promise<readonly string[]> {
  const files = expected(await buildKernelInventory(root));
  const directory = path.join(root, 'docs/90-generated/kernel');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(files)) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/kernel/${name}`);
  }
  return Object.freeze(written);
}

export async function checkKernelDocumentation(root = process.cwd()): Promise<readonly KernelIssue[]> {
  const files = expected(await buildKernelInventory(root));
  const issues: KernelIssue[] = [];
  for (const [name, content] of Object.entries(files)) {
    const file = `docs/90-generated/kernel/${name}`;
    const actual = await readOptional(path.join(root, file));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        area: 'contract',
        code: actual === null ? 'KERNEL_DOC_MISSING' : 'KERNEL_DOC_DRIFT',
        file,
        message: actual === null
          ? 'A generált HTTP-kernel dokumentum hiányzik.'
          : 'A generált HTTP-kernel dokumentum nincs szinkronban a lifecycle contractokkal.',
      });
    }
  }
  return Object.freeze(issues);
}
