import { defineFormContract } from '@/platform/forms/form-contract';

export const luckyNumberFormDefinition = defineFormContract({
  schemaVersion: 1,
  id: 'demo.lucky-number.generate',
  execution: 'server-action',
  mutation: true,
  component: 'LuckyNumberForm',
  deliveryContractId: 'demo.lucky-number.generate.action',
  extractor: 'luckyNumberRawInput',
  schema: 'luckyNumberFormSchema',
  actionState: 'GenerateLuckyNumberActionState',
  errorMapper: 'mapLuckyNumberIssues',
  unknownFields: 'reject',
  progressiveEnhancement: 'supported',
  authentication: 'optional',
  tenant: 'none',
  idempotency: 'none',
  idempotencyRequired: false,
  fields: [
    {
      name: 'minimum',
      id: 'lucky-number-minimum',
      kind: 'number',
      multiplicity: 'single',
      required: true,
      presentationOnly: false,
      authority: false,
      errorCodes: ['FORM_INVALID_TYPE', 'FORM_CUSTOM'],
    },
    {
      name: 'maximum',
      id: 'lucky-number-maximum',
      kind: 'number',
      multiplicity: 'single',
      required: true,
      presentationOnly: false,
      authority: false,
      errorCodes: ['FORM_INVALID_TYPE', 'FORM_CUSTOM'],
    },
    {
      name: 'intent',
      id: 'lucky-number-intent',
      kind: 'hidden',
      multiplicity: 'single',
      required: true,
      presentationOnly: true,
      authority: false,
      errorCodes: ['FORM_INVALID_VALUE'],
    },
  ],
  intents: [
    {
      value: 'generate',
      label: 'Generálás Server Actionnel',
      operation: 'demo.commands.generateLuckyNumber',
    },
  ],
  filePolicy: null,
} as const);
