import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildCompositionInventory } from './inventory';
import { renderCompositionGraph } from './render';
import type { CompositionInventory, CompositionIssue } from './types';

const HEADER = [
  '<!-- Generated by Winzard Forge. -->',
  '<!-- Source: explicit composition.definition.ts contracts. -->',
  '<!-- Do not edit directly. -->',
].join('\n');

function cell(value: string | null | readonly string[]): string {
  if (value === null || value === '') return '-';
  if (typeof value !== 'string') return value.length > 0 ? value.join('<br>') : '-';
  return value.replaceAll('|', '\\|');
}

function inventoryDocument(inventory: CompositionInventory): string {
  const rows = inventory.services.map((service) =>
    `| \`${service.id}\` | ${service.kind} | ${cell(service.port)} | ${service.implementation} | ${service.lifetime} | ${service.runtime} | ${service.visibility} | ${cell(service.dependencies)} |`).join('\n');
  return `${HEADER}\n\n# Service inventory\n\nComposition SHA-256: \`${inventory.fingerprint}\`\n\n| Service | Kind | Port | Implementation | Lifetime | Runtime | Visibility | Dependencies |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows}\n`;
}

function graphDocument(inventory: CompositionInventory): string {
  return `${HEADER}\n\n# Composition graph\n\nComposition SHA-256: \`${inventory.fingerprint}\`\n\n\`\`\`mermaid\n${renderCompositionGraph(inventory, 'mermaid')}\n\`\`\`\n`;
}

function lifetimeDocument(inventory: CompositionInventory): string {
  const rows = inventory.services.map((service) =>
    `| ${service.lifetime} | \`${service.id}\` | ${service.requestState ? 'yes' : 'no'} | ${service.disposable ? 'yes' : 'no'} |`).join('\n');
  return `${HEADER}\n\n# Service lifetimes\n\nComposition SHA-256: \`${inventory.fingerprint}\`\n\n| Lifetime | Service | Request state | Disposable |\n| --- | --- | --- | --- |\n${rows}\n`;
}

function securityDocument(inventory: CompositionInventory): string {
  const rows = inventory.issues.length > 0
    ? inventory.issues.map((item) => `| ${item.severity} | ${item.area} | \`${item.code}\` | \`${item.file}\` | ${item.message.replaceAll('|', '\\|')} |`).join('\n')
    : '| pass | - | - | - | No composition issue detected. |';
  return `${HEADER}\n\n# Composition security status\n\nComposition SHA-256: \`${inventory.fingerprint}\`\n\n| Severity | Area | Code | File | Message |\n| --- | --- | --- | --- | --- |\n${rows}\n`;
}

function expected(inventory: CompositionInventory): Readonly<Record<string, string>> {
  return Object.freeze({
    'service-inventory.md': inventoryDocument(inventory),
    'composition-graph.md': graphDocument(inventory),
    'service-lifetimes.md': lifetimeDocument(inventory),
    'composition-security-status.md': securityDocument(inventory),
  });
}

async function optional(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateCompositionDocumentation(
  root = process.cwd(),
): Promise<readonly string[]> {
  const absoluteRoot = path.resolve(root);
  const files = expected(await buildCompositionInventory(absoluteRoot));
  const directory = path.join(absoluteRoot, 'docs/90-generated/composition');
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  for (const [name, content] of Object.entries(files)) {
    await writeFile(path.join(directory, name), content, 'utf8');
    written.push(`docs/90-generated/composition/${name}`);
  }
  return Object.freeze(written.sort());
}

export async function checkCompositionDocumentation(
  root = process.cwd(),
): Promise<readonly CompositionIssue[]> {
  const absoluteRoot = path.resolve(root);
  const files = expected(await buildCompositionInventory(absoluteRoot));
  const issues: CompositionIssue[] = [];
  for (const [name, content] of Object.entries(files)) {
    const file = `docs/90-generated/composition/${name}`;
    const actual = await optional(path.join(absoluteRoot, file));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        area: 'generation',
        code: actual === null ? 'COMPOSITION_DOC_MISSING' : 'COMPOSITION_DOC_DRIFT',
        file,
        message: actual === null
          ? 'A generált composition dokumentum hiányzik.'
          : 'A generált composition dokumentum nincs szinkronban a service graphpal.',
      });
    }
  }
  return Object.freeze(issues);
}
