import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildCompositionInventory } from './inventory';
import type { CompositionInventory, CompositionIssue } from './types';

const HEADER = '// Generated by Winzard Forge.\n// Do not edit directly.\n';

function rootImportSpecifier(source: string): string {
  const withoutExtension = source.replace(/\.(?:ts|tsx|js|jsx|mjs|cjs)$/u, '');
  return withoutExtension.startsWith('src/')
    ? `@/${withoutExtension.slice('src/'.length)}`
    : withoutExtension;
}

function rootBinding(index: number): string {
  return `compositionRoot${index}`;
}

function registry(inventory: CompositionInventory): string {
  const startupRoots = inventory.roots.filter(({ runtime }) => runtime !== 'edge');
  const imports = startupRoots
    .map((root, index) =>
      `import { ${root.exportName} as ${rootBinding(index)} } from ${JSON.stringify(rootImportSpecifier(root.source))};`)
    .join('\n');
  const instances = startupRoots
    .map((root, index) =>
      `  Object.freeze({ id: ${JSON.stringify(root.id)}, value: ${rootBinding(index)} }),`)
    .join('\n');
  return `${HEADER}\nimport 'server-only';\n${imports ? `${imports}\n` : ''}\nexport const generatedCompositionFingerprint = ${JSON.stringify(inventory.fingerprint)};\n\nexport const generatedCompositionRoots = ${JSON.stringify(inventory.roots, null, 2)} as const;\n\nexport const generatedCompositionRegistry = ${JSON.stringify(inventory.services, null, 2)} as const;\n\nexport const generatedCompositionRootInstances = Object.freeze([\n${instances}\n] as const);\n`;
}

function graphManifest(inventory: CompositionInventory): string {
  return `${JSON.stringify({
    schemaVersion: 1,
    fingerprint: inventory.fingerprint,
    roots: inventory.roots.map(({ id, source, exportName, runtime, services }) => ({ id, source, exportName, runtime, services })),
    services: inventory.services.map((service) => ({
      id: service.id,
      capability: service.capability,
      kind: service.kind,
      implementation: service.implementation,
      port: service.port,
      source: service.source,
      exportName: service.exportName,
      lifetime: service.lifetime,
      runtime: service.runtime,
      visibility: service.visibility,
      dependencies: service.dependencies,
      decorators: service.decorators,
      aliases: service.aliases,
      tags: service.tags,
      priority: service.priority,
      configKeys: service.configKeys,
      secretKeys: service.secretKeys,
      disposable: service.disposable,
      requestState: service.requestState,
    })),
  }, null, 2)}\n`;
}

async function sourceManifest(root: string, inventory: CompositionInventory): Promise<string> {
  const sources = await Promise.all(inventory.definitions.map(async ({ file }) => ({
    path: file,
    sha256: createHash('sha256').update(await readFile(path.join(root, file), 'utf8')).digest('hex'),
  })));
  return `${JSON.stringify({ schemaVersion: 1, fingerprint: inventory.fingerprint, sources }, null, 2)}\n`;
}

export async function expectedCompositionFiles(
  root = process.cwd(),
): Promise<Readonly<Record<string, string>>> {
  const absoluteRoot = path.resolve(root);
  const inventory = await buildCompositionInventory(absoluteRoot);
  return Object.freeze({
    'src/generated/composition/registry.ts': registry(inventory),
    'src/generated/composition/graph-manifest.json': graphManifest(inventory),
    'src/generated/composition/source-manifest.json': await sourceManifest(absoluteRoot, inventory),
  });
}

async function optional(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

export async function generateComposition(
  root = process.cwd(),
): Promise<readonly string[]> {
  const absoluteRoot = path.resolve(root);
  const files = await expectedCompositionFiles(absoluteRoot);
  const written: string[] = [];
  for (const [relative, content] of Object.entries(files)) {
    const target = path.join(absoluteRoot, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
    written.push(relative);
  }
  return Object.freeze(written.sort());
}

export async function checkCompositionGeneration(
  root = process.cwd(),
): Promise<readonly CompositionIssue[]> {
  const absoluteRoot = path.resolve(root);
  const files = await expectedCompositionFiles(absoluteRoot);
  const issues: CompositionIssue[] = [];
  for (const [relative, content] of Object.entries(files)) {
    const actual = await optional(path.join(absoluteRoot, relative));
    if (actual !== content) {
      issues.push({
        severity: 'error',
        area: 'generation',
        code: actual === null ? 'COMPOSITION_GENERATED_MISSING' : 'COMPOSITION_GENERATED_DRIFT',
        file: relative,
        message: actual === null
          ? 'A generált composition artifact hiányzik.'
          : 'A generált composition artifact nincs szinkronban a definition fájlokkal.',
      });
    }
  }
  return Object.freeze(issues);
}
