import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildTestingInventory } from './inventory';
import { renderTestingMatrix, renderTestingQuarantine } from './render';
import type { TestingInventory, TestingIssue } from './types';

const GENERATED_DIRECTORY = 'docs/90-generated/testing';

function renderSuiteDocumentation(inventory: TestingInventory): string {
  return [
    '# Testing suites',
    '',
    '| ID | Owner | Layer | Runtime | Command | CI job |',
    '| --- | --- | --- | --- | --- | --- |',
    ...inventory.suites.map((suite) =>
      `| ${suite.id} | ${suite.owner} | ${suite.layer} | ${suite.runtime} | \`${suite.command}\` | ${suite.ciJob} |`),
  ].join('\n');
}

function outputFiles(root: string, inventory: Awaited<ReturnType<typeof buildTestingInventory>>) {
  const header = '<!-- Generated by Winzard Forge. Do not edit directly. -->\n\n';
  return Object.freeze([
    {
      path: path.join(root, GENERATED_DIRECTORY, 'testing-suites.md'),
      content: `${header}${renderSuiteDocumentation(inventory)}\n`,
    },
    {
      path: path.join(root, GENERATED_DIRECTORY, 'testing-matrix.md'),
      content: `${header}# Testing matrix\n\n${renderTestingMatrix(inventory)}\n`,
    },
    {
      path: path.join(root, GENERATED_DIRECTORY, 'testing-quarantine.md'),
      content: `${header}# Testing quarantine\n\n${renderTestingQuarantine(inventory)}\n`,
    },
  ]);
}

export async function generateTestingDocumentation(root: string): Promise<readonly string[]> {
  const inventory = await buildTestingInventory(root);
  const files = outputFiles(root, inventory);
  await mkdir(path.join(root, GENERATED_DIRECTORY), { recursive: true });
  for (const file of files) await writeFile(file.path, file.content, 'utf8');
  return Object.freeze(files.map((file) => path.relative(root, file.path).split(path.sep).join('/')));
}

export async function checkTestingDocumentation(root: string): Promise<readonly TestingIssue[]> {
  const inventory = await buildTestingInventory(root);
  const issues: TestingIssue[] = [];
  for (const file of outputFiles(root, inventory)) {
    let current: string | null = null;
    try {
      current = await readFile(file.path, 'utf8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    if (current !== file.content) {
      issues.push(Object.freeze({
        severity: 'error' as const,
        code: 'TEST_DOCUMENTATION_DRIFT',
        file: path.relative(root, file.path).split(path.sep).join('/'),
        message: current === null ? 'A generált testing dokumentum hiányzik.' : 'A generált testing dokumentum eltér a forráscontracttól.',
      }));
    }
  }
  return Object.freeze(issues);
}
