import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { EVENT_COMMANDS } from '../src/events/cli';
import { checkEventGeneration, generateEvents } from '../src/events/generator';
import { buildEventInventory } from '../src/events/inventory';
async function file(root: string, target: string, content: string): Promise<void> { const absolute = path.join(root, target); await mkdir(path.dirname(absolute), { recursive: true }); await writeFile(absolute, content, 'utf8'); }
async function fixture(): Promise<string> { const root = await mkdtemp(path.join(os.tmpdir(), 'winzard-events-')); await file(root, 'src/domain/order-placed.ts', 'export type OrderPlaced = unknown;\n'); await file(root, 'src/application/place-order.ts', 'export class PlaceOrder {}\n'); await file(root, 'src/application/handler.ts', 'export const handler = async () => {};\n'); await file(root, 'src/composition/order.event.definition.ts', `export const orderEvents = defineEvents({ schemaVersion: 1, id: 'orders', events: [{ id: 'orders.order.placed', type: 'orders.order.placed', category: 'domain', version: 1, source: 'src/domain/order-placed.ts', export: 'OrderPlaced', producer: 'src/application/place-order.ts', classification: 'internal', tenantScoped: true, aliases: [], handlers: [{ id: 'orders.order-placed.audit', source: 'src/application/handler.ts', export: 'handler', phase: 'transactional', failurePolicy: 'fail-fast', before: [], after: [], idempotent: true }] }] });\n`); return root; }
describe('Forge event platform', () => { it('deterministic inventoryt épít', async () => { const root = await fixture(); const first = await buildEventInventory(root); const second = await buildEventInventory(root); expect(first.issues.filter(({ severity }) => severity === 'error')).toEqual([]); expect(first.fingerprint).toBe(second.fingerprint); expect(first.events[0]?.handlers[0]?.id).toBe('orders.order-placed.audit'); }); it('publikálja a teljes event és messaging command felületet', () => { expect(EVENT_COMMANDS).toContain('event:check'); expect(EVENT_COMMANDS).toContain('message:compat'); expect(EVENT_COMMANDS).toContain('outbox:replay-plan'); }); it('ciklust és durable policy hibát jelez', async () => { const root = await fixture(); const definition = path.join(root, 'src/composition/order.event.definition.ts'); let source = await readFile(definition, 'utf8'); source = source.replace("before: [], after: [], idempotent: true", "before: ['orders.order-placed.audit'], after: [], idempotent: false, maximumAttempts: 0").replace("failurePolicy: 'fail-fast'", "failurePolicy: 'retry-durable'"); await writeFile(definition, source, 'utf8'); const codes = (await buildEventInventory(root)).issues.map(({ code }) => code); expect(codes).toContain('EVENT_HANDLER_DURABLE_POLICY_INVALID'); expect(codes).toContain('EVENT_HANDLER_DEPENDENCY_CYCLE'); }); it('generated artifact driftet észlel', async () => { const root = await fixture(); await generateEvents(root); expect(await checkEventGeneration(root)).toHaveLength(0); const registry = path.join(root, 'src/generated/events/registry.ts'); await writeFile(registry, (await readFile(registry, 'utf8')) + 'drift\n', 'utf8'); expect(await checkEventGeneration(root)).toContainEqual(expect.objectContaining({ code: 'EVENT_GENERATED_DRIFT' })); }); });
