import type { WinzardManifest } from '../manifest';
import type { ConfigurationDefinition } from './types';

const introduced = '0.1.0';

const applicationDefinitions: readonly ConfigurationDefinition[] = [
  {
    key: 'APP_URL',
    owner: 'application-shell',
    capability: 'application-shell',
    description: 'Az alkalmazás megbízható canonical originje szerveroldali URL-generáláshoz.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'url', protocols: ['http:', 'https:'], originOnly: true },
    example: 'http://localhost:3000',
    introduced,
  },
  {
    key: 'APP_NAME',
    owner: 'application-shell',
    capability: 'application-shell',
    description: 'Az alkalmazás szerveroldali, nem üres megjelenítési neve.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 128 },
    example: 'Atlas',
    introduced,
  },
  {
    key: 'APP_STAGE',
    owner: 'application-shell',
    capability: 'application-shell',
    description: 'A deployment operációs stage-e; nem helyettesíti a NODE_ENV értéket.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'enum', values: ['local', 'development', 'preview', 'staging', 'production'] },
    example: 'local',
    introduced,
  },
  {
    key: 'LOG_LEVEL',
    owner: 'observability',
    capability: 'application-shell',
    description: 'A process-szintű strukturált naplózás minimális súlyossága.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'enum', values: ['debug', 'info', 'warn', 'error'] },
    example: 'info',
    introduced,
  },
  {
    key: 'NEXT_PUBLIC_APP_NAME',
    owner: 'public-ui',
    capability: 'application-shell',
    description: 'A böngészőbundle-be beágyazható publikus alkalmazásnév.',
    required: true,
    phase: 'public-client',
    classification: 'public',
    rebuildRequired: true,
    restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 128 },
    example: 'Atlas',
    introduced,
  },
];



const kernelConfigurationDefinitions: readonly ConfigurationDefinition[] = [
  {
    key: 'APP_ID', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Stabil alkalmazásazonosító cache-, telemetry- és deploymentnamespace-ekhez.',
    required: true, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 64 },
    example: 'winzard-app', introduced,
  },
  {
    key: 'APP_REGION', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A deployment explicit régiója; nem része az APP_STAGE értékének.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 64 },
    example: 'local', defaultValue: 'local', introduced,
  },
  {
    key: 'GIT_COMMIT', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Az artifact forráscommitja; release buildben a stabil buildazonosság kötelező inputja.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 7, maximumLength: 64 },
    example: '0000000', introduced,
  },
  {
    key: 'BUILD_ID', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Az immutable build hordozható azonosítója; hiányában local módban a commitazonosító használható.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 128 },
    example: 'local-build', defaultValue: 'local-build', introduced,
  },
  {
    key: 'DEPLOYMENT_ID', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Egy konkrét rollout valamennyi példányán egységes deploymentazonosító.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 128 },
    example: 'local-deployment', defaultValue: 'local-deployment', introduced,
  },
  {
    key: 'SOURCE_DATE_EPOCH', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Reprodukálható buildhez használt nem negatív Unix timestamp másodpercben.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'integer', minimum: 0, maximum: 9_007_199_254_740_991 },
    example: '0', defaultValue: '0', introduced,
  },
  {
    key: 'DEFAULT_LOCALE', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A támogatott locale-listából választott alapértelmezett locale.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'enum', values: ['hu', 'en'] },
    example: 'hu', defaultValue: 'hu', introduced,
  },
  {
    key: 'ENABLED_LOCALES', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Vesszővel tagolt, zárt locale-allowlist.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'csv-enum', values: ['hu', 'en'], minimumItems: 1 },
    example: 'hu,en', defaultValue: 'hu,en', introduced,
  },
  {
    key: 'TRUSTED_HOSTS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A request Host validálására szolgáló exact vagy egycímkés wildcard allowlist.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 2048 },
    example: 'localhost:3000,127.0.0.1,[::1]', defaultValue: 'localhost:3000', introduced,
  },
  {
    key: 'SERVER_ACTION_ALLOWED_ORIGINS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A Next.js Server Action CSRF-origin ellenőrzésének szűk buildidős allowlistje.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 2048 },
    example: 'localhost:3000', defaultValue: 'localhost:3000', introduced,
  },
  {
    key: 'SERVER_ACTION_BODY_SIZE_LIMIT', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A Server Action request body buildidős felső méretkorlátja.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 2, maximumLength: 32 },
    example: '1mb', defaultValue: '1mb', introduced,
  },
  {
    key: 'NEXT_SERVER_ACTIONS_ENCRYPTION_KEY', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A Next.js Server Action payloadok build- és rolloutszinten konzisztens, 256 bites AES-GCM kulcsa.',
    required: false, phase: 'build-time', classification: 'secret',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'secret', minimumLength: 43 },
    example: '<generate-32-byte-base64-server-action-key>', introduced,
  },
  {
    key: 'TRUSTED_PROXY_MODE', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A proxy trust explicit módja: none, fixed-hops vagy cidr.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'enum', values: ['none', 'fixed-hops', 'cidr'] },
    example: 'none', defaultValue: 'none', introduced,
  },
  {
    key: 'TRUSTED_PROXY_CIDRS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'CIDR proxy trust mód explicit IPv4/IPv6 allowlistje.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 9, maximumLength: 2048 },
    example: '127.0.0.1/32', defaultValue: '127.0.0.1/32', introduced,
  },
  {
    key: 'TRUSTED_PROXY_HOPS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Fixed-hop proxy trust módban a megbízható proxy hopok száma.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 1, maximum: 8 },
    example: '1', defaultValue: '1', introduced,
  },
  {
    key: 'NEXT_DIST_DIR', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A projektgyökéren belül maradó Next.js buildkönyvtár.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 256 },
    example: '.next', defaultValue: '.next', introduced,
  },
  {
    key: 'NEXT_OUTPUT_STANDALONE', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Explicit deployment-policy a Next.js standalone output engedélyezéséhez.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'boolean' },
    example: 'false', defaultValue: 'false', introduced,
  },
  {
    key: 'PRODUCTION_BROWSER_SOURCE_MAPS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Production browser source map explicit, review-köteles buildpolicyja.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'boolean' },
    example: 'false', defaultValue: 'false', introduced,
  },
  {
    key: 'PRODUCTION_BROWSER_SOURCE_MAPS_WAIVER', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Production source map engedélyezésekor kötelező dokumentált waiver hivatkozás.',
    required: false, phase: 'build-time', classification: 'internal',
    rebuildRequired: true, restartRequired: false,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 128 },
    example: 'not-required', defaultValue: 'not-required', introduced,
  },
  {
    key: 'KERNEL_VERBOSE_DIAGNOSTICS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Részletes, de minden esetben redaktált kernel-diagnosztika kapcsolója.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'boolean' },
    example: 'false', defaultValue: 'false', introduced,
  },
  {
    key: 'CACHE_SCHEMA_VERSION', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'A cache-entry formátum és namespace pozitív egész schema verziója.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 1, maximum: 10_000 },
    example: '1', defaultValue: '1', introduced,
  },
  {
    key: 'COMPOSITION_HASH', owner: 'service-composition', capability: 'service-composition',
    description: 'Opcionális deployment-elvárás a canonical composition fingerprinthez; auto esetén nincs külső pin.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 4, maximumLength: 64 },
    example: 'auto', defaultValue: 'auto', introduced,
  },
  {
    key: 'RUNTIME_WRITABLE_ROOT', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Az immutable application artifacton kívüli, korlátozott runtime írható gyökér.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'string', minimumLength: 1, maximumLength: 512 },
    example: '/tmp/winzard', defaultValue: '/tmp/winzard', introduced,
  },
  {
    key: 'WORKER_CONCURRENCY', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Worker entrypoint korlátozott párhuzamossága.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 1, maximum: 128 },
    example: '4', defaultValue: '4', introduced,
  },
  {
    key: 'WORKER_VISIBILITY_TIMEOUT_MS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Worker lease/visibility timeout ezredmásodpercben.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 1_000, maximum: 86_400_000 },
    example: '60000', defaultValue: '60000', introduced,
  },
  {
    key: 'WORKER_SHUTDOWN_GRACE_MS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Worker graceful shutdown időablaka ezredmásodpercben.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 1_000, maximum: 300_000 },
    example: '30000', defaultValue: '30000', introduced,
  },
  {
    key: 'WORKER_POLL_INTERVAL_MS', owner: 'kernel-configuration', capability: 'kernel-configuration',
    description: 'Worker polling intervalluma ezredmásodpercben.',
    required: false, phase: 'process-start', classification: 'internal',
    rebuildRequired: false, restartRequired: true,
    validation: { kind: 'integer', minimum: 10, maximum: 60_000 },
    example: '1000', defaultValue: '1000', introduced,
  },
];

const databaseDefinitions: readonly ConfigurationDefinition[] = [
  {
    key: 'DATABASE_URL',
    owner: 'prisma-postgresql',
    capability: 'prisma-postgresql',
    description: 'A PostgreSQL runtime kapcsolat credentialt is tartalmazó DSN-je.',
    required: true,
    phase: 'process-start',
    classification: 'secret',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'postgres-url' },
    example: 'postgresql://user:password@localhost:5432/atlas',
    introduced,
  },
  {
    key: 'DATABASE_POOL_MAX',
    owner: 'prisma-postgresql',
    capability: 'prisma-postgresql',
    description: 'Egy process maximális adatbázis-kapcsolatszáma.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'integer', minimum: 1, maximum: 100 },
    example: '10',
    introduced,
  },
  {
    key: 'DATABASE_CONNECTION_TIMEOUT_MS',
    owner: 'prisma-postgresql',
    capability: 'prisma-postgresql',
    description: 'Adatbázis-kapcsolódási timeout ezredmásodpercben.',
    required: true,
    phase: 'process-start',
    classification: 'internal',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'integer', minimum: 100, maximum: 60_000 },
    example: '5000',
    introduced,
  },
];

const authenticationDefinitions: readonly ConfigurationDefinition[] = [
  {
    key: 'AUTH_SECRET',
    owner: 'authentication',
    capability: 'authentication',
    description: 'Az authentication capability nagy entrópiájú szerveroldali signing secretje.',
    required: true,
    phase: 'process-start',
    classification: 'secret',
    rebuildRequired: false,
    restartRequired: true,
    validation: { kind: 'secret', minimumLength: 32 },
    example: '<generate-at-least-32-random-characters>',
    introduced,
  },
];

export const allKnownConfigurationDefinitions = Object.freeze([
  ...applicationDefinitions,
  ...kernelConfigurationDefinitions,
  ...databaseDefinitions,
  ...authenticationDefinitions,
].sort((left, right) => left.key.localeCompare(right.key)));

export function configurationDefinitionsForManifest(
  manifest: WinzardManifest,
): readonly ConfigurationDefinition[] {
  const capabilities = new Set(manifest.capabilities);
  return allKnownConfigurationDefinitions.filter((definition) =>
    definition.capability === 'application-shell'
      ? capabilities.has('next-app')
      : capabilities.has(definition.capability));
}

export function configurationDefinitionByKey(
  manifest: WinzardManifest,
  key: string,
): ConfigurationDefinition | null {
  return configurationDefinitionsForManifest(manifest).find((definition) => definition.key === key) ?? null;
}
