import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { checkEventDocumentation, generateEventDocumentation } from './docs';
import { checkEventGeneration, generateEvents } from './generator';
import { buildEventInventory, inspectEvents } from './inventory';
import { renderEventGraph, renderEventInspection, renderEventIssues, renderEventList } from './render';

export const EVENT_COMMANDS = Object.freeze([
  'event:list', 'event:inspect', 'event:graph', 'event:check', 'event:aliases', 'event:docs', 'event:generate',
  'message:contracts', 'message:inspect', 'message:compat',
  'outbox:status', 'outbox:check', 'outbox:replay-plan', 'inbox:status', 'dead-letter:list',
] as const);
const COMMANDS = new Set<string>(EVENT_COMMANDS);
function parse(values: readonly string[]) { const positionals: string[] = []; const options = new Map<string, string | true>(); for (let index = 1; index < values.length; index += 1) { const value = values[index] ?? ''; if (!value.startsWith('--')) { positionals.push(value); continue; } const equals = value.indexOf('='); if (equals > 2) { options.set(value.slice(0, equals), value.slice(equals + 1)); continue; } const next = values[index + 1]; if (next && !next.startsWith('--')) { options.set(value, next); index += 1; } else options.set(value, true); } return { positionals, options }; }
function hasErrors(values: readonly { severity: string }[]): boolean { return values.some(({ severity }) => severity === 'error'); }
async function prismaSchema(root: string): Promise<string> { try { return await readFile(path.join(root, 'prisma/schema.prisma'), 'utf8'); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return ''; throw error; } }
export async function runEventCli(args: readonly string[]): Promise<boolean> {
  const command = args[0] ?? ''; if (!COMMANDS.has(command)) return false;
  const parsed = parse(args); const option = (name: string) => { const value = parsed.options.get(name); return typeof value === 'string' ? value : null; }; const flag = (name: string) => parsed.options.get(name) === true;
  const project = option('--project') ?? '.'; const root = path.resolve(process.cwd(), project); const json = flag('--json');
  if (command === 'event:generate') { const result = flag('--check') ? await checkEventGeneration(root) : await generateEvents(root); console.log(json ? JSON.stringify({ result }, null, 2) : Array.isArray(result) && result.every((item) => typeof item === 'string') ? `GENERATED: ${result.length} event artifact` : renderEventIssues(result as never, 'event:generate --check')); if (!flag('--check') ? false : hasErrors(result as never)) process.exitCode = 1; return true; }
  if (command === 'event:docs') { const result = flag('--check') ? await checkEventDocumentation(root) : await generateEventDocumentation(root); console.log(json ? JSON.stringify({ result }, null, 2) : Array.isArray(result) && result.every((item) => typeof item === 'string') ? `GENERATED: ${result.length} event document` : renderEventIssues(result as never, 'event:docs --check')); if (flag('--check') && hasErrors(result as never)) process.exitCode = 1; return true; }
  const inventory = await buildEventInventory(root);
  if (command === 'event:list') console.log(json ? JSON.stringify(inventory, null, 2) : renderEventList(inventory));
  else if (command === 'event:inspect' || command === 'message:inspect') { const query = parsed.positionals[0]; if (!query) throw Object.assign(new Error(`A ${command} parancshoz event type vagy ID szükséges.`), { exitCode: 2 }); const records = inspectEvents(inventory, query).filter((record) => command === 'event:inspect' || record.category === 'integration'); console.log(json ? JSON.stringify({ records }, null, 2) : renderEventInspection(records)); if (records.length === 0) process.exitCode = 1; }
  else if (command === 'event:graph') { const format = option('--format') ?? 'text'; if (format !== 'text' && format !== 'mermaid' && format !== 'json') throw Object.assign(new Error('--format csak text, mermaid vagy json lehet.'), { exitCode: 2 }); console.log(format === 'json' || json ? JSON.stringify({ events: inventory.events, fingerprint: inventory.fingerprint }, null, 2) : renderEventGraph(inventory, format)); }
  else if (command === 'event:check') console.log(json ? JSON.stringify({ issues: inventory.issues, fingerprint: inventory.fingerprint }, null, 2) : renderEventIssues(inventory.issues, 'event:check'));
  else if (command === 'event:aliases') { const aliases = inventory.events.flatMap(({ type, aliases }) => aliases.map((alias) => ({ alias, type }))); console.log(json ? JSON.stringify({ aliases }, null, 2) : aliases.map(({ alias, type }) => `${alias} → ${type}`).join('\n') || 'No event aliases.'); }
  else if (command === 'message:contracts') { const events = inventory.events.filter(({ category }) => category === 'integration'); console.log(json ? JSON.stringify({ events }, null, 2) : renderEventList({ ...inventory, events })); }
  else if (command === 'message:compat') { const type = parsed.positionals[0]; if (!type) throw Object.assign(new Error('A message:compat parancshoz event type szükséges.'), { exitCode: 2 }); const records = inventory.events.filter((event) => event.category === 'integration' && (event.type === type || event.aliases.includes(type))); const compatible = records.length === 1 && records[0]?.payloadSchema !== null; console.log(json ? JSON.stringify({ type, compatible, records }, null, 2) : compatible ? `PASS: ${type} verziózott schema contracttal rendelkezik.` : `FAIL: ${type} nem egyértelmű vagy schema nélküli.`); if (!compatible) process.exitCode = 1; }
  else { const schema = await prismaSchema(root); const required = ['OutboxMessage', 'InboxMessage', 'DeadLetterMessage']; const models = required.map((model) => ({ model, present: new RegExp(`model\\s+${model}\\b`, 'u').test(schema) })); const configured = models.every(({ present }) => present); if (command === 'outbox:check') { console.log(json ? JSON.stringify({ configured, models }, null, 2) : configured ? 'PASS: outbox/inbox/dead-letter Prisma contract.' : `FAIL: hiányzó modellek: ${models.filter(({ present }) => !present).map(({ model }) => model).join(', ')}`); if (!configured) process.exitCode = 1; } else if (command === 'outbox:replay-plan') console.log(json ? JSON.stringify({ dryRun: true, configured, steps: ['validate schema and consumer version', 'check idempotency', 'select tenant-scoped messages', 'rate-limit replay', 'record operator audit'] }, null, 2) : 'DRY-RUN replay plan: validate → idempotency → tenant filter → rate limit → audit.'); else console.log(json ? JSON.stringify({ configured, runtimeInspection: false, command }, null, 2) : `${command}: schema ${configured ? 'configured' : 'not configured'}; runtime adatlekérdezéshez application adapter szükséges.`); }
  if (hasErrors(inventory.issues)) process.exitCode = 1; return true;
}
