import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildEventInventory } from './inventory';
import type { EventIssue } from './types';

const FILES = ['docs/90-generated/events/event-inventory.md', 'docs/90-generated/events/event-graph.md', 'docs/90-generated/events/handler-registry.md', 'docs/90-generated/events/security-status.md'] as const;
function header(fingerprint: string): string { return `<!-- Generated by Winzard Forge. -->\n<!-- Do not edit directly. -->\n\nEvent registry SHA-256: \`${fingerprint}\`\n\n`; }
async function content(root: string): Promise<Readonly<Record<(typeof FILES)[number], string>>> {
  const inventory = await buildEventInventory(root); const h = header(inventory.fingerprint);
  const inventoryRows = inventory.events.map((event) => `| \`${event.type}\` | ${event.category} | v${event.version} | ${event.classification} | ${event.tenantScoped ? 'yes' : 'no'} | ${event.handlers.length} |`).join('\n') || '| - | - | - | - | - | 0 |';
  const graph = ['```mermaid', 'graph LR', ...inventory.events.flatMap((event) => [`  ${safe(event.producer)}["${event.producer}"] --> ${safe(event.type)}["${event.type}"]`, ...event.handlers.map((handler) => `  ${safe(event.type)} --> ${safe(handler.id)}["${handler.id}"]`)]), '```'].join('\n');
  const handlers = inventory.events.flatMap((event) => event.handlers.map((handler) => `| \`${event.type}\` | \`${handler.id}\` | ${handler.phase} | ${handler.failurePolicy} | ${handler.idempotent ? 'yes' : 'no'} |`)).join('\n') || '| - | - | - | - | - |';
  const issueRows = inventory.issues.map((issue) => `| ${issue.severity} | \`${issue.code}\` | \`${issue.file}\` | ${issue.message.replace(/\|/gu, '\\|')} |`).join('\n') || '| pass | - | - | No event issue detected. |';
  return {
    'docs/90-generated/events/event-inventory.md': `${h}# Event inventory\n\n| Event type | Category | Version | Classification | Tenant scoped | Handlers |\n| --- | --- | --- | --- | --- | --- |\n${inventoryRows}\n`,
    'docs/90-generated/events/event-graph.md': `${h}# Event graph\n\n${graph}\n`,
    'docs/90-generated/events/handler-registry.md': `${h}# Handler registry\n\n| Event type | Handler | Phase | Failure policy | Idempotent |\n| --- | --- | --- | --- | --- |\n${handlers}\n`,
    'docs/90-generated/events/security-status.md': `${h}# Event security and architecture status\n\n| Severity | Code | File | Message |\n| --- | --- | --- | --- |\n${issueRows}\n`,
  };
}
function safe(value: string): string { return value.replace(/[^A-Za-z0-9_]/gu, '_'); }
export async function generateEventDocumentation(root: string): Promise<readonly string[]> { const output = await content(root); for (const [file, value] of Object.entries(output)) { await mkdir(path.dirname(path.join(root, file)), { recursive: true }); await writeFile(path.join(root, file), value, 'utf8'); } return Object.freeze([...FILES]); }
export async function checkEventDocumentation(root: string): Promise<readonly EventIssue[]> { const expected = await content(root); const issues: EventIssue[] = []; for (const file of FILES) { let actual = ''; try { actual = await readFile(path.join(root, file), 'utf8'); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } if (actual !== expected[file]) issues.push({ severity: 'error', area: 'generation', code: 'EVENT_DOCUMENTATION_DRIFT', file, message: 'A generated event dokumentáció hiányzik vagy eltér.' }); } return Object.freeze(issues); }
