import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { buildEventInventory } from './inventory';
import type { EventIssue } from './types';

const FILES = ['src/generated/events/registry.ts', 'src/generated/events/graph-manifest.json', 'src/generated/events/source-manifest.json'] as const;

function projectImport(source: string): string {
  const withoutExtension = source.replace(/\.(?:[cm]?[jt]sx?)$/u, '');
  return withoutExtension.startsWith('src/') ? `@/${withoutExtension.slice(4)}` : withoutExtension;
}

function runtimeRegistry(inventory: Awaited<ReturnType<typeof buildEventInventory>>): string {
  const handlers = inventory.events.flatMap((event) => event.handlers.map((handler) => ({ eventType: event.type, handler })));
  const imports = handlers.map(({ handler }, index) =>
    `import { ${handler.exportName} as eventHandler${index} } from '${projectImport(handler.source)}';`);
  const byEvent = new Map<string, string[]>();
  handlers.forEach(({ eventType }, index) => {
    const values = byEvent.get(eventType) ?? [];
    values.push(`eventHandler${index}`);
    byEvent.set(eventType, values);
  });
  const entries = inventory.events.map(({ type }) =>
    `  ${JSON.stringify(type)}: Object.freeze([${(byEvent.get(type) ?? []).join(', ')}]),`);

  return [
    '/* Generated by Winzard Forge. Do not edit. */',
    "import type { EventRegistry } from '@/platform/events/contract';",
    ...imports,
    '',
    'export const eventHandlerRegistry = Object.freeze({',
    ...entries,
    '}) satisfies EventRegistry;',
    '',
    `export const eventRegistryManifest = Object.freeze(${JSON.stringify({ schemaVersion: 1, fingerprint: inventory.fingerprint, events: inventory.events }, null, 2)} as const);`,
    '',
  ].join('\n');
}

async function content(root: string): Promise<Readonly<Record<(typeof FILES)[number], string>>> {
  const inventory = await buildEventInventory(root);
  const sources = await Promise.all(inventory.definitions.map(async ({ file }) => ({ file, sha256: createHash('sha256').update(await readFile(path.join(root, file), 'utf8')).digest('hex') })));
  return {
    'src/generated/events/registry.ts': runtimeRegistry(inventory),
    'src/generated/events/graph-manifest.json': `${JSON.stringify({ schemaVersion: 1, fingerprint: inventory.fingerprint, events: inventory.events.map(({ type, producer, handlers }) => ({ type, producer, handlers: handlers.map(({ id, phase }) => ({ id, phase })) })) }, null, 2)}\n`,
    'src/generated/events/source-manifest.json': `${JSON.stringify({ schemaVersion: 1, fingerprint: inventory.fingerprint, sources }, null, 2)}\n`,
  };
}
export async function generateEvents(root: string): Promise<readonly string[]> {
  const output = await content(root);
  for (const [file, value] of Object.entries(output)) { await mkdir(path.dirname(path.join(root, file)), { recursive: true }); await writeFile(path.join(root, file), value, 'utf8'); }
  return Object.freeze([...FILES]);
}
export async function checkEventGeneration(root: string): Promise<readonly EventIssue[]> {
  const expected = await content(root); const issues: EventIssue[] = [];
  for (const file of FILES) {
    let actual = ''; try { actual = await readFile(path.join(root, file), 'utf8'); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    if (actual !== expected[file]) issues.push({ severity: 'error', area: 'generation', code: 'EVENT_GENERATED_DRIFT', file, message: 'A generated event artifact hiányzik vagy eltér a definition forrástól.' });
  }
  return Object.freeze(issues);
}
