import { defineComposition } from '@/platform/composition/contract';

export const demoComposition = defineComposition({
  schemaVersion: 1,
  id: 'demo.lucky-number',
  capability: 'service-composition',
  roots: [
    {
      id: 'demo.lucky-number.root',
      source: 'src/composition/demo.server.ts',
      export: 'demoModule',
      runtime: 'nodejs',
      services: [
        'demo.lucky-number.query.get',
        'demo.lucky-number.command.generate',
        'demo.lucky-number.policy',
      ],
    },
  ],
  services: [
    {
      id: 'demo.lucky-number.random.node',
      kind: 'infrastructure',
      implementation: 'NodeCryptoRandomIntegerGenerator',
      port: 'RandomIntegerGenerator',
      source: 'src/modules/demo/lucky-number/infrastructure/random/node-crypto-random-integer-generator.ts',
      export: 'NodeCryptoRandomIntegerGenerator',
      lifetime: 'process',
      runtime: 'nodejs',
      visibility: 'private',
      dependencies: [],
      decorators: ['demo.lucky-number.random.validated'],
    },
    {
      id: 'demo.lucky-number.random.validated',
      kind: 'decorator',
      implementation: 'ValidatedRandomIntegerGenerator',
      port: 'RandomIntegerGenerator',
      source: 'src/modules/demo/lucky-number/infrastructure/random/validated-random-integer-generator.ts',
      export: 'ValidatedRandomIntegerGenerator',
      lifetime: 'process',
      runtime: 'nodejs',
      visibility: 'private',
      dependencies: ['demo.lucky-number.random.node'],
    },
    {
      id: 'demo.lucky-number.range-rules',
      kind: 'registry',
      implementation: 'luckyNumberRangeRules',
      source: 'src/modules/demo/lucky-number/application/rules/lucky-number-range-rule.ts',
      export: 'luckyNumberRangeRules',
      lifetime: 'static',
      runtime: 'universal',
      visibility: 'private',
      dependencies: [],
      tags: ['demo.lucky-number.range-rule'],
      priority: 100,
    },
    {
      id: 'demo.lucky-number.query.get',
      kind: 'application',
      implementation: 'GetLuckyNumber',
      source: 'src/modules/demo/lucky-number/application/queries/get-lucky-number.ts',
      export: 'GetLuckyNumber',
      lifetime: 'process',
      runtime: 'nodejs',
      visibility: 'public',
      dependencies: [
        'demo.lucky-number.random.validated',
        'demo.lucky-number.range-rules',
      ],
      aliases: ['demo.query.lucky-number'],
    },
    {
      id: 'demo.lucky-number.policy',
      kind: 'application',
      implementation: 'LuckyNumberPolicy',
      source: 'src/modules/demo/lucky-number/application/policies/lucky-number.policy.ts',
      export: 'LuckyNumberPolicy',
      lifetime: 'process',
      runtime: 'universal',
      visibility: 'public',
      dependencies: [],
    },
    {
      id: 'demo.lucky-number.command.generate',
      kind: 'application',
      implementation: 'GenerateLuckyNumber',
      source: 'src/modules/demo/lucky-number/application/commands/generate-lucky-number.ts',
      export: 'GenerateLuckyNumber',
      lifetime: 'process',
      runtime: 'nodejs',
      visibility: 'public',
      dependencies: [
        'demo.lucky-number.query.get',
        'demo.lucky-number.policy',
      ],
      aliases: ['demo.command.generate-lucky-number'],
    },
  ],
});
