import { defineComposition } from '@/platform/composition/contract';

export const eventComposition = defineComposition({
  schemaVersion: 1,
  id: 'demo.events',
  capability: 'event-dispatching',
  roots: [{
    id: 'demo.events.root',
    source: 'src/composition/event-runtime.server.ts',
    export: 'eventRuntime',
    runtime: 'nodejs',
    services: ['demo.events.dispatcher', 'demo.events.trace', 'demo.events.command.dispatch', 'demo.events.handler.record'],
  }],
  services: [
    {
      id: 'demo.events.handler.record',
      kind: 'application',
      implementation: 'recordLuckyNumberGenerated',
      source: 'src/modules/demo/lucky-number/application/event-handlers/record-lucky-number-generated.ts',
      export: 'recordLuckyNumberGenerated',
      lifetime: 'process',
      runtime: 'universal',
      visibility: 'private',
      dependencies: [],
      tags: ['event-handler'],
    },
    {
      id: 'demo.events.trace',
      kind: 'platform',
      implementation: 'RecordingEventDispatchTrace',
      source: 'src/platform/events/recording-trace.ts',
      export: 'RecordingEventDispatchTrace',
      lifetime: 'process',
      runtime: 'universal',
      visibility: 'private',
      dependencies: [],
    },
    {
      id: 'demo.events.dispatcher',
      kind: 'platform',
      implementation: 'SequentialDomainEventDispatcher',
      port: 'DomainEventDispatcher',
      source: 'src/platform/events/dispatcher.ts',
      export: 'SequentialDomainEventDispatcher',
      lifetime: 'process',
      runtime: 'universal',
      visibility: 'private',
      dependencies: ['demo.events.handler.record', 'demo.events.trace'],
    },
    {
      id: 'demo.events.command.dispatch',
      kind: 'application',
      implementation: 'DispatchLuckyNumberGenerated',
      source: 'src/modules/demo/lucky-number/application/commands/dispatch-lucky-number-generated.ts',
      export: 'DispatchLuckyNumberGenerated',
      lifetime: 'process',
      runtime: 'universal',
      visibility: 'public',
      dependencies: ['demo.events.dispatcher'],
    },
  ],
});
